// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $SessionType = {
  "work": $.$expr_Literal<$SessionType>;
  "break": $.$expr_Literal<$SessionType>;
} & $.EnumType<"default::SessionType", ["work", "break"]>;
const SessionType: $SessionType = $.makeType<$SessionType>(_.spec, "3b210963-1d2c-11f0-9036-61fa762d7b11", _.syntax.literal);

export type $EntryλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "entryTime": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "entryJournal": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "entryName": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, true>;
  "entryEfficiency": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, true>;
  "<entry[is Session]": $.LinkDesc<$Session, $.Cardinality.Many, {}, false, false,  false, false>;
  "<entry": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Entry = $.ObjectType<"default::Entry", $EntryλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::Entry">;
const $Entry = $.makeType<$Entry>(_.spec, "1282b063-1d24-11f0-a4de-f5da7e03cf7d", _.syntax.literal);

const Entry: $.$expr_PathNode<$.TypeSet<$Entry, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Entry, $.Cardinality.Many), null);

export type $SessionλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "sessionTime": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "sessionIndex": $.PropertyDesc<_std.$int32, $.Cardinality.One, false, false, false, true>;
  "sessionDuration": $.PropertyDesc<_std.$duration, $.Cardinality.One, false, false, false, true>;
  "sessionType": $.PropertyDesc<$SessionType, $.Cardinality.One, false, false, false, true>;
  "entry": $.LinkDesc<$Entry, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
}>;
type $Session = $.ObjectType<"default::Session", $SessionλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::Session">;
const $Session = $.makeType<$Session>(_.spec, "413915d3-1d20-11f0-a432-936835f555bb", _.syntax.literal);

const Session: $.$expr_PathNode<$.TypeSet<$Session, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Session, $.Cardinality.Many), null);



export { SessionType, $Entry, Entry, $Session, Session };

type __defaultExports = {
  "SessionType": typeof SessionType;
  "Entry": typeof Entry;
  "Session": typeof Session
};
const __defaultExports: __defaultExports = {
  "SessionType": SessionType,
  "Entry": Entry,
  "Session": Session
};
export default __defaultExports;
